export const initialSettings = {
  brandName: 'BuildForge Studio',
  tagline: 'An online development studio for modern businesses.',
  coreMessage: 'We build digital systems that solve real business problems.',
  businessEmail: 'hello@buildforgestudio.com',
  whatsappNumber: '+91 98765 43210',
  whatsappMessage: 'Hi BuildForge Studio, I would like to discuss a project or quick development task.',
  socialLinks: {
    linkedin: 'https://linkedin.com/company/buildforgestudio',
    github: 'https://github.com/buildforgestudio',
    twitter: 'https://twitter.com/buildforgestudio',
    instagram: 'https://instagram.com/buildforgestudio',
  },
  metaTitle: 'BuildForge Studio | Custom Web Systems, SaaS MVPs & Quick Dev Tasks',
  metaDescription: 'BuildForge Studio is an independent online development studio delivering custom web applications, SaaS MVPs, and rapid development bug fixes.',
  primaryCtaText: 'Start a Project',
  footerText: '© 2026 BuildForge Studio. All rights reserved. Built with precision for modern businesses.',
  availabilityStatus: 'Available for New Projects & Quick Tasks (Q3/Q4 2026)',
};

export const initialServices = [
  {
    title: 'Custom Web Applications',
    slug: 'custom-web-applications',
    shortDescription: 'Full-stack web applications tailored to streamline operations and deliver scalable client experiences.',
    fullDescription: 'We build end-to-end web applications with custom database architectures, robust REST APIs, authenticated client portals, and responsive user interfaces that eliminate operational bottlenecks.',
    startingPrice: '$1,200+',
    features: [
      'Custom React / Next.js frontends with modern UI/UX',
      'Scalable Node.js & Express RESTful API backends',
      'Secure MongoDB / PostgreSQL database design',
      'Role-based authentication & session controls',
      'Zero-downtime deployment & CI/CD pipelines',
    ],
    icon: 'AppWindow',
    ctaText: 'Build a Web App',
    displayOrder: 1,
    published: true,
  },
  {
    title: 'SaaS MVPs & Product Prototyping',
    slug: 'saas-mvps-product-prototyping',
    shortDescription: 'Fast-track your software product from concept to a tested, production-ready MVP in weeks.',
    fullDescription: 'Designed for founders and businesses launching digital products. We turn your product requirements into a live, scalable, monetizable SaaS product with clean architecture.',
    startingPrice: '$2,500+',
    features: [
      'Multi-tenant architecture & user account management',
      'Stripe & payment gateway subscriptions integration',
      'Interactive metrics & admin dashboards',
      'Modular microservices or clean monolithic codebases',
      'Complete documentation & automated test suites',
    ],
    icon: 'Rocket',
    ctaText: 'Launch an MVP',
    displayOrder: 2,
    published: true,
  },
  {
    title: 'Business Management & Internal Tools',
    slug: 'business-management-internal-tools',
    shortDescription: 'Custom internal software, inventory engines, CRM boards, and workflows that replace chaotic spreadsheets.',
    fullDescription: 'Off-the-shelf software rarely fits custom business processes. We engineer bespoke internal platforms that automate repetitive tasks, manage team pipelines, and synthesize critical business metrics.',
    startingPrice: '$1,800+',
    features: [
      'Tailored CRM, lead pipelines & inventory management',
      'Automated notifications via WhatsApp, Email & SMS',
      'Role-specific access controls (Admin, Staff, Manager)',
      'Custom reporting, PDF generation & data exports',
      'Seamless integration with third-party webhooks',
    ],
    icon: 'Layers',
    ctaText: 'Build Custom System',
    displayOrder: 3,
    published: true,
  },
  {
    title: 'API Engineering & Integrations',
    slug: 'api-engineering-integrations',
    shortDescription: 'Connect disjointed systems, build high-throughput APIs, and orchestrate automated data pipelines.',
    fullDescription: 'We connect payment gateways, CRM databases, AI models, ERPs, and cloud services with bulletproof error handling, webhook queues, and rate-limiting security.',
    startingPrice: '$600+',
    features: [
      'Secure REST & GraphQL API development',
      'Payment gateways (Stripe, Razorpay, PayPal) integration',
      'Third-party cloud & webhook automation',
      'API rate limiting, caching & security hardening',
      'Comprehensive Postman / OpenAPI documentation',
    ],
    icon: 'Cpu',
    ctaText: 'Integrate APIs',
    displayOrder: 4,
    published: true,
  },
];

export const initialQuickTasks = [
  {
    title: 'React & Frontend Bug Fixes',
    slug: 'react-frontend-bug-fixes',
    description: 'Fix state management bugs, rendering loops, broken responsive layouts, hydration errors, and component crashes.',
    startingPrice: '$35',
    technology: 'React / Vite / Next.js / Tailwind',
    icon: 'Code',
    displayOrder: 1,
    published: true,
  },
  {
    title: 'Node.js & Express API Fixes',
    slug: 'nodejs-express-api-fixes',
    description: 'Resolve route errors, async unhandled rejections, controller crashes, broken middleware, and payload issues.',
    startingPrice: '$45',
    technology: 'Node.js / Express / REST APIs',
    icon: 'Server',
    displayOrder: 2,
    published: true,
  },
  {
    title: 'MongoDB Schema & Query Debugging',
    slug: 'mongodb-schema-query-debugging',
    description: 'Optimize slow aggregation pipelines, fix indexing, debug Mongoose schema validations, and resolve connection timeouts.',
    startingPrice: '$50',
    technology: 'MongoDB / Mongoose / Atlas',
    icon: 'Database',
    displayOrder: 3,
    published: true,
  },
  {
    title: 'Third-Party API Integration',
    slug: 'third-party-api-integration',
    description: 'Connect third-party services like Cloudinary, Stripe, SendGrid, Twilio, OpenAI, or Google APIs into your app.',
    startingPrice: '$65',
    technology: 'REST APIs / Webhooks / SDKs',
    icon: 'Plug',
    displayOrder: 4,
    published: true,
  },
  {
    title: 'Authentication & Session Repair',
    slug: 'authentication-session-repair',
    description: 'Fix broken JWT cookies, CORS authorization headers, bcrypt password hashing bugs, and token refresh loops.',
    startingPrice: '$60',
    technology: 'JWT / OAuth / Cookies / Sessions',
    icon: 'ShieldCheck',
    displayOrder: 5,
    published: true,
  },
  {
    title: 'Deployment, Vercel & Render Setup',
    slug: 'deployment-vercel-render-setup',
    description: 'Fix build failures, SPA 404 rewrite issues on Vercel, Render backend deployment crashes, and environment configs.',
    startingPrice: '$40',
    technology: 'Vercel / Render / Git / CI/CD',
    icon: 'CloudUpload',
    displayOrder: 6,
    published: true,
  },
  {
    title: 'Small Feature & Form Addition',
    slug: 'small-feature-form-addition',
    description: 'Add a new interactive form, search filter bar, modal workflow, file uploader, or custom UI component to your app.',
    startingPrice: '$55',
    technology: 'Full-Stack MERN',
    icon: 'PlusCircle',
    displayOrder: 7,
    published: true,
  },
  {
    title: 'Performance & Lighthouse Optimization',
    slug: 'performance-lighthouse-optimization',
    description: 'Audit and speed up slow React bundles, reduce image payloads, optimize database queries, and achieve 90+ Lighthouse score.',
    startingPrice: '$75',
    technology: 'Vite / Bundle Optimization / Caching',
    icon: 'Zap',
    displayOrder: 8,
    published: true,
  },
];

export const initialProcessSteps = [
  {
    stepNumber: '01',
    title: 'Discover & Scope',
    description: 'We unpack your core objectives, system requirements, data models, and technical constraints to establish a clear roadmap.',
    details: [
      'In-depth requirements analysis and user flow breakdown',
      'Technical feasibility audit and technology selection',
      'Defined deliverables, transparent pricing, and delivery timeline',
    ],
    displayOrder: 1,
    published: true,
  },
  {
    stepNumber: '02',
    title: 'Architect & Plan',
    description: 'We structure the database schemas, API contracts, component hierarchies, and interactive states before writing code.',
    details: [
      'Mongoose schema & relational data modeling',
      'Centralized REST API specifications and route mapping',
      'High-fidelity UI/UX layout and state planning',
    ],
    displayOrder: 2,
    published: true,
  },
  {
    stepNumber: '03',
    title: 'Build & Test',
    description: 'We engineer your system with production-grade code, unit tests, responsive styling, and robust error safeguards.',
    details: [
      'Component-scoped frontend styling and responsive design',
      'Secure backend controllers with validation & rate limiting',
      'Continuous local testing across screen sizes & network conditions',
    ],
    displayOrder: 3,
    published: true,
  },
  {
    stepNumber: '04',
    title: 'Deploy & Support',
    description: 'We push to production cloud infrastructure (Vercel + Render + MongoDB Atlas), verify live operations, and provide walkthroughs.',
    details: [
      'Production environment variable verification & CORS audit',
      'Cloudinary media storage setup & database indexing',
      'Post-launch warranty, code documentation, and maintenance support',
    ],
    displayOrder: 4,
    published: true,
  },
];

export const initialProjects = [
  {
    title: 'PulseBoard SaaS Analytics & Team CRM',
    slug: 'pulseboard-saas-analytics-team-crm',
    shortDescription: 'A real-time metrics dashboard and deal pipeline system for high-velocity software startups.',
    fullDescription: 'PulseBoard is a high-performance business dashboard that aggregates subscription revenues, user retention metrics, and sales pipelines into an unified control room. Engineered with real-time WebSockets, custom MongoDB aggregation queries, and an ultra-clean modern UI.',
    category: 'SaaS MVP',
    thumbnail: {
      imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
      publicId: 'seed_pulseboard_thumb',
      caption: 'PulseBoard Analytics Command Center',
    },
    gallery: [
      {
        imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
        publicId: 'seed_pulseboard_1',
        caption: 'Executive revenue tracking dashboard',
      },
      {
        imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
        publicId: 'seed_pulseboard_2',
        caption: 'Interactive pipeline and conversion analytics',
      },
    ],
    technologies: ['React', 'Node.js', 'Express', 'MongoDB Atlas', 'Vite', 'Recharts', 'JWT'],
    features: [
      'Real-time revenue metrics with dynamic date range filtering',
      'Drag-and-drop lead conversion kanban board',
      'Automated weekly email summaries and PDF report exports',
      'Role-based multi-user workspaces with invite tokens',
      'Sub-second query response times with optimized indexing',
    ],
    problem: 'The client was managing customer retention and sales leads across four disconnected spreadsheets, leading to lost customer renewals and conflicting metrics.',
    solution: 'BuildForge Studio architected a centralized MERN web application with automated data aggregation pipelines and role-based access for sales managers.',
    liveDemoUrl: 'https://pulseboard-demo.buildforgestudio.com',
    caseStudyUrl: '',
    featured: true,
    published: true,
    displayOrder: 1,
  },
  {
    title: 'ArchiNova Property Ecosystem',
    slug: 'archinova-property-ecosystem',
    shortDescription: 'An enterprise real estate consulting portal featuring interactive inventory maps and automated lead triage.',
    fullDescription: 'A multi-tier property marketplace and lead qualification engine for luxury real estate firms. Includes dynamic micro-market listings, floor plan viewers, and instant CRM synchronization.',
    category: 'Business System',
    thumbnail: {
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      publicId: 'seed_archinova_thumb',
      caption: 'ArchiNova Luxury Portal',
    },
    gallery: [
      {
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
        publicId: 'seed_archinova_1',
        caption: 'Luxury listing catalog with high-res galleries',
      },
      {
        imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
        publicId: 'seed_archinova_2',
        caption: 'Interactive lead capture and floor plan explorer',
      },
    ],
    technologies: ['React 18', 'Express.js', 'MongoDB', 'Cloudinary API', 'Framer Motion', 'REST APIs'],
    features: [
      'Cloudinary dynamic image optimization and auto-resizing',
      'Multi-criteria property search (BHK, Price Range, Location)',
      'Direct WhatsApp and automated enquiry routing',
      'Integrated administrative content management system',
      'Full Lighthouse 98+ mobile performance rating',
    ],
    problem: 'Property listings suffered from slow page loads due to uncompressed 10MB images, resulting in high bounce rates and lost high-value buyer enquiries.',
    solution: 'Engineered an automated Cloudinary image transformation pipeline and a lightning-fast React frontend backed by cached MongoDB queries.',
    liveDemoUrl: 'https://archinova-demo.buildforgestudio.com',
    caseStudyUrl: '',
    featured: true,
    published: true,
    displayOrder: 2,
  },
  {
    title: 'CloudSync Webhook & Data Bridge',
    slug: 'cloudsync-webhook-data-bridge',
    shortDescription: 'High-throughput middleware connecting eCommerce storefronts to legacy warehousing databases.',
    fullDescription: 'A resilient event-driven microservice that captures, transforms, and synchronizes eCommerce order webhooks into legacy ERP and inventory systems with guaranteed delivery and retry queues.',
    category: 'Internal Tool',
    thumbnail: {
      imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
      publicId: 'seed_cloudsync_thumb',
      caption: 'CloudSync Event Processing Engine',
    },
    gallery: [
      {
        imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
        publicId: 'seed_cloudsync_1',
        caption: 'Live webhook throughput and error monitoring',
      },
    ],
    technologies: ['Node.js', 'Express', 'MongoDB', 'Redis', 'Docker', 'REST API'],
    features: [
      'Webhook signature verification and replay attack prevention',
      'Exponential backoff retry queues for failed warehouse requests',
      'Real-time admin monitoring dashboard with dead-letter queue inspection',
      'Process 10,000+ payload transformations per minute',
      'Zero data loss architecture with transactional MongoDB sessions',
    ],
    problem: 'Order spikes caused legacy warehouse endpoints to drop requests, creating order fulfillment discrepancies and customer refund disputes.',
    solution: 'Built an asynchronous queueing proxy in Node.js that buffers incoming order spikes and reliably feeds warehouse systems at a controlled rate.',
    liveDemoUrl: 'https://cloudsync-demo.buildforgestudio.com',
    caseStudyUrl: '',
    featured: true,
    published: true,
    displayOrder: 3,
  },
];

export const initialTestimonials = [
  {
    clientName: 'David Sterling',
    company: 'Sterling Growth Labs',
    role: 'Founder & CEO',
    quote: 'BuildForge Studio solved our critical API latency and React state bottlenecks in under 48 hours. Their communication, clean code standards, and production mindset are unmatched.',
    avatar: {
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      publicId: 'seed_testimonial_1',
    },
    rating: 5,
    published: true,
    displayOrder: 1,
  },
  {
    clientName: 'Elena Rostova',
    company: 'Veloce Logistics',
    role: 'VP of Product',
    quote: 'We commissioned BuildForge to build our internal dispatch dashboard from scratch. They delivered a flawless MERN system ahead of schedule with zero post-launch bugs.',
    avatar: {
      imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
      publicId: 'seed_testimonial_2',
    },
    rating: 5,
    published: true,
    displayOrder: 2,
  },
];
